name: singular
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  retrofit: ^3.0.1+1
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.5.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.1
  internet_connection_checker: ^0.0.1+4
  provider: ^6.0.3
  dio: ^4.0.6
  like_button: ^2.0.4
  line_icons: ^2.0.1
  shimmer: ^2.0.0
  lottie: ^1.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: 4.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env


